### ISSUE TITLE
Rust idiom on your project

### ISSUE THREAD

**Issue by syw-saoul** [RustCrypto/elliptic-curves#145]
Hello,
I have a question on the Rust idiom.

I found the rust idom on the new constructor like below
"new is the constructor convention in Rust, and users expect it to exist"
from https://rust-lang.github.io/api-guidelines/interoperability.html

IMHO, your EC apis on the new constructor do not follow Rust idiom.
"pub fn Signer::new(secret_key: &SecretKey<C>) -> Result<Self, Error>"
It tells me, construct may be exist or not.

1. I want to know your opinion
2. Do you have any legacy design pattern or Rust idioms for this project?

**Comment by tarcieri** [comment]
Note that this project uses [clippy](https://github.com/rust-lang/rust-clippy) to check for idiomatic Rust.

This usage of `::new` is idomatic:

https://github.com/RustCrypto/elliptic-curves/blob/master/k256/src/ecdsa/signer.rs#L35

To quote the full section of the documentation you're talking about in context:

> Note that it is common and expected for types to implement both `Default` and an empty `new` constructor. `new` is the constructor convention in Rust, and users expect it to exist, so if it is reasonable for the basic constructor to take no arguments, then it should, even if it is functionally identical to `default`.

What that's saying is if you have a type that impl's `Default`, it still makes sense to define `pub fn new() -> Self` as well.

However, that's not really applicable to this case: `Signer` does not impl `Default` (because it needs a key to sign with).
