### ISSUE TITLE
Generic curve arithmetic

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/elliptic-curves#22]
One of the goals of the `elliptic-curve` crate is to be able to write code that's generic over (at least Weierstrass) elliptic curve types.

Now that the `p256` and `k256` crates have arithmetic implementations (thanks @str4d and @tuxxy!), an open question is how to write code that's generic over the underlying `AffinePoint` and/or `ProjectivePoint` types.

It seems like `AffinePoint` and `ProjectivePoint` could benefit from having traits which at the very least are bounded by the point arithmetic they must support.

It also seems like there needs to be some trait connecting the two of them which can be used to access the `From` impls and arithmetic (e.g. `Add`) between the two different point types.

Finally, it seems like there needs to be a trait a `weierstrass::Curve` type can impl which provides that curve's `AffinePoint` and `ProjectivePoint` types as associated types.

Curious if people think this is a good idea and what those traits might look like.

cc @tuxxy

**Comment by tarcieri** [comment]
@tuxxy brought up scalars on #23 

It might make sense to replace the existing `Scalar` struct in the `elliptic-curve` crate with a trait as well:

https://docs.rs/elliptic-curve/0.3.0/elliptic_curve/scalar/struct.Scalar.html

**Comment by tuxxy** [comment]
I have some curve generic traits that I used for a library I am building with @nucypher called Twinkle. I've changed a lot of the backend since, but I have some trait definitions for `Scalar` and `Point`.

As an example, here's the definition for `Point`:

```rust
pub trait Point: Sized {
    type Backend: Backend<Point = Self>;
    /// This can be used to swap out the library point type with a custom type.
    /// If no such swapping is done, this should simply be Self.
    type BackendPoint: Sized;

    // Arithmetic functions
    fn point_mul(lhs: <Self::Backend as Backend>::Scalar, rhs: Self) -> Self;
    fn point_add(lhs: Self, rhs: Self) -> Self;
    fn point_sub(lhs: Self, rhs: Self) -> Self;
    fn point_neg(point_val: Self) -> Self;

    fn point_eq(lhs: &Self, rhs: &Self) -> bool;

    // Constants
    fn basepoint() -> Self;
    fn identity() -> Self;

    // Helper functions
    fn new() -> Self {
        Self::identity()
    }
    fn from_backend_point(point: Self::BackendPoint) -> Self;
    fn get_backend_point(self) -> Self::BackendPoint;
}
```

Obviously, this won't work straight out of the box, but I can imagine a very similar architecture. These traits get implemented _on the backend type)_ (e.g. Ristretto's `Scalar`) and then we have blanket impls for operations on two types called `TwinkleScalar` and `TwinklePoint` so that they're generic to 1) a `Backend` and 2) requires that the `Backend` type have two associated types that implement `Scalar` and `Point`.

What I'm thinking is that the `elliptic-curve` crate would probably have its own `Scalar` and `Point` type that has something like a "backend" for each curve, though this might be able to be simplified a lot more.

**Comment by str4d** [comment]
See the `group` crate for another starting point, that we've been using in Zcash. I'm almost done refactoring the `ff` crate, and `group` will be next, so this is a good time to be discussing these traits 🙂

**Comment by tarcieri** [comment]
@str4d awesome! If you have a crate with some existing traits to use for this, all the better

**Comment by tuxxy** [comment]
I'm finding myself interested in using this crate, but I also need scalar arithmetic. Since we presently lack this, it makes sense for me to potentially scope this out a bit more.

Why would it make sense to refactor `Scalar` to a trait? It makes more sense to me to implement the curve-specific type `Order` (perhaps with a trait) and then make `Scalar` generic over it, as per #13.

Also, I'm not very keen on the idea of a type simply named `Order`. IMHO, it seems it would be far more usable to name it something specific to the curve. In practice, no one is interested in operating on scalars over an order -- they only care about scalars for a specific curve, which confers the order inherently.

**Comment by str4d** [comment]
I'm pretty happy with the group and curve trait API I've arrived at in zkcrypto/group#6, so I'll spend some time thinking about refactoring this crate in terms of it. I'm interested to hear feedback in that issue.

**Comment by tarcieri** [comment]
I added an `elliptic_curve::ops::Invert` trait in https://github.com/RustCrypto/traits/pull/228 which looks like the following:

```rust
/// Perform an inversion on a field element (i.e. base field element or scalar)
pub trait Invert {
    /// Field element type
    type Output;

    /// Invert a field element.
    fn invert(&self) -> CtOption<Self::Output>;
}
```

This made it possible to eliminate the specifics of blinding scalar inversions from the ECDSA signing API, which was helpful:

https://github.com/RustCrypto/elliptic-curves/pull/99/files#diff-995156456abcc4ccf4d937223154cb43

But I also didn't really put any thought into this trait design, and I'm curious if there are other places we could source a similar trait from, or alternative designs to consider /cc @nickray @str4d

Also note that I'd like to cut another release of `elliptic-curve` fairly soon, like in the next week or so!

**Comment by tarcieri** [comment]
I implemented the `ff::{Field, PrimeField}` and `group::{Group, Curve}` traits on `k256` in #164 and `p256` in #169. With that, I'd say we now support generic curve arithmetic, at least as well as the `ff` and `group` crates do.
