### ISSUE TITLE
ECDH API concerns

### ISSUE THREAD

**Issue by rozbb** [RustCrypto/elliptic-curves#236]
I was previously using `p256::AffinePoint` in version 0.4 to represent pubkeys. I suppose that's still possible, but it looks like there's now more explicit support for ECDH operations.

My issue is that `elliptic_curve::ecdh::PublicKey` is defined to be an `EncodedPoint`, which means that no validation is performed upon deserialization (at least as far as I can tell from the [`from_bytes`](https://docs.rs/elliptic-curve/0.6.5/src/elliptic_curve/sec1.rs.html#80-96) function). However, in [SECG](https://secg.org/sec1-v2.pdf) page 12 (and also in the HPKE spec) it says when doing uncompressed point deserialization, you need to check that the coordinates represent a point on the curve.

Not sure what the best fix is here. Although a simple one would be to just make `type PublicKey = AffinePoint` instead. This would work because the constructor of `AffinePoint` does the ECDH "partial validation" in SECG section 3.2.3. Namely, it checks that the point is on the curve and that it's not O. For non-prime curves, it might be desirable to make `PublicKey` its own type so that a user can opt into partial or full validation (the distinction doesn't exist for prime curves because all full-validation additionally checks is membership in the prime subgroup, which is trivially the case in prime order curves).

**Comment by tarcieri** [comment]
Elliptic curve implementations in this repo always validate points, compressed or uncompressed, when decoding from `sec1::EncodedPoint` to `AffinePoint`. The invariant of `AffinePoint` types is to always represent a valid curve point. The curve implementations in this repository use complete projective formulas, and the traits provided by the `elliptic-curve` crate are intended for use with them.

Uncompressed points are always checked to ensure they are valid for the curve equation, and it is not possible to perform any curve arithmetic until these checks have been performed. Here is how the `p256` crate implements `AffinePoint` decoding for example:

https://github.com/RustCrypto/elliptic-curves/blob/550ea95/p256/src/arithmetic/affine.rs#L127-L144

In the case of ECDH, this validation is deferred to the `diffie_hellman` function itself, which is fallible:

https://github.com/RustCrypto/traits/blob/d77bef5/elliptic-curve/src/ecdh.rs#L84-L93

The reason that the ECDH API uses `sec1::EncodedPoint` is to keep the API simple, so the end user doesn't have to take a more circuitous path of `sec1::EncodedPoint` -> `AffinePoint` in order to perform Diffie-Hellman. However, it might make sense to introduce an `AffinePoint` newtype, similar to [`ecdsa::VerifyKey`](https://docs.rs/ecdsa/0.8.5/ecdsa/verify/struct.VerifyKey.html).

The only benefit of that would be to make the `diffie_hellman` function infallible. It would have no effect on security.

**Comment by rozbb** [comment]
You're totally right, and that title was very misleading. Yes, validation is always done, and the thing I'm complaining about is just about when it's done.

I think my intuition for why validation should be done at deserialization time is just because it makes debugging easier. Specifically, failing as soon as possible, and as close to the edges of the API as possible, gives a better idea of what's wrong. E.g., "DH failed, where did this key come from?" versus "this key won't load".

If that's agreeable, I can write a PR to make ECDH pubkeys into AffinePoints. Is there a reason you'd prefer a newtype over a type alias?

**Comment by tarcieri** [comment]
> If that's agreeable, I can write a PR to make ECDH pubkeys into AffinePoints. Is there a reason you'd prefer a newtype over a type alias?

The `AffinePoint` type is defined by the underlying curve implementation, so any functionality we add to it needs to be replicated in all of the underlying crates.

`AffinePoint` also represents a secret in certain contexts, so many of the operations defined on it leverage `subtle` and `CtOption`, which is somewhat abrasive for the `PublicKey` use case.

It may make sense to define a generally useful `PublicKey` type similar to the existing [`SecretKey`](https://docs.rs/elliptic-curve/0.6.6/elliptic_curve/secret_key/struct.SecretKey.html) type, which wraps up things like encoding in a similar way to [`ecdsa::VerifyKey`](https://docs.rs/ecdsa/0.8.5/ecdsa/verify/struct.VerifyKey.html), but unlike `sec1::EncodedPoint` always represents a valid curve point.
