### ISSUE TITLE
Expose field arithmetic

### ISSUE THREAD

**Issue by omershlo** [RustCrypto/elliptic-curves#29]
Is there a plan to expose `FieldElement` for P-256? 
(motivation: I am looking to implement a Trait in [Curv](https://github.com/KZen-networks/curv/blob/master/src/elliptic/curves/traits.rs))

**Comment by str4d** [comment]
I don't think that `FieldElement` should be exposed in arbitrary generic code, because there are very few reasons to be operating directly on curve point coordinates outside of the curve implementation.
- ECDSA is unfortunately one of them 😞 but that can be handled with an ECDSA-specific trait implemented by curves themselves (which is the direction we are likely to go for the `ecdsa` crate).
- Representing curve points in ZKP circuits requires access to coordinates, but only for nested curves, so it seems more appropriate to have traits implemented only on those nested curves.

What is the use case you have that requires access to `FieldElement`?

**Comment by omershlo** [comment]
Thanks for clarifying !

**Comment by tarcieri** [comment]
@omershlo you might check out `fiat-rust` if you'd like a `p256` implementation that exposes its internals:

https://github.com/scipr-lab/zexe/pull/176
