### ISSUE TITLE
Safely access secret scalar bytes

### ISSUE THREAD

**Issue by andrewwhitehead** [RustCrypto/elliptic-curves#488]
I'm updating from k256/p256 0.9 to 0.10, and the `as_scalar_bytes()` method has been removed with the switch to the new scalar backing type. Ideally I'm looking for a way to access the BE byte representation without creating copies that aren't zeroized, but the `FieldBytes` type is just a `GenericArray`. Is there a good way to do this?

**Comment by tarcieri** [comment]
`elliptic-curve` v0.11 changed the internal representation of `SecretKey` from (the now removed) `ScalarBytes` to `ScalarCore`, which is a newtype wrapper for a `crypto_bigint::UInt` type which represents the scalar as an array of word-sized limbs.

This representation is more amenable to directly performing arithmetic, since the corresponding `Scalar` types are also internally `crypto_bigint::UInt`. However, it is detrimental to the case where you want a byte array instead of an array of words.

I'd be curious to know the use case, but that said, to support this sort of usage you'd need to define your own replacement type for `ScalarBytes`, or make a copy every time.

**Comment by andrewwhitehead** [comment]
Thanks, I've ended up using the following (which is really just a copy of the implementation in crypto-bigint) to copy into an immovable buffer.

```rust
use elliptic_curve::{
    bigint::{Encoding, Limb},
    Curve, SecretKey,
};

pub fn write_sk<C: Curve>(sk: &SecretKey<C>, out: &mut [u8]) {
    let limbs = sk.as_scalar_core().as_limbs();
    debug_assert_eq!(out.len(), Limb::BYTE_SIZE * limbs.len());

    for (src, dst) in limbs
        .iter()
        .rev()
        .cloned()
        .zip(out.chunks_exact_mut(Limb::BYTE_SIZE))
    {
        dst.copy_from_slice(&src.to_be_bytes());
    }
}
```

**Comment by tarcieri** [comment]
If you'd just like a big endian serialization of the inner secret scalar that `SecretKey` wraps, you can just call `SecretKey::to_be_bytes`:

https://docs.rs/elliptic-curve/latest/elliptic_curve/struct.SecretKey.html#method.to_be_bytes
