### ISSUE TITLE
Why is `NonZeroScalar::invert()` fallible?

### ISSUE THREAD

**Issue by fjarri** [RustCrypto/elliptic-curves#499]
It feels like, since we know that it is nonzero, there should be some `fn invert(&self) -> NonZeroScalar`, or at least `-> Scalar`, instead of `-> CtOption<Scalar>`, which will never have the `None` variant. Isn't guaranteed invertibility one of the major uses of a `NonZeroScalar` type?

**Comment by tarcieri** [comment]
The issue is [`Invert` is a trait](https://docs.rs/elliptic-curve/latest/elliptic_curve/ops/trait.Invert.html) and the current definition uses `CtOption<Self::Output>` as a return type.

It would probably make sense to get that `CtOption` out of the trait signature and allow `NonZeroScalar`'s impl to be infallible. Other impls could choose to return `CtOption<Self::Output>`.

**Comment by fjarri** [comment]
Or perhaps we could have `Invert` (infallible) and `TryInvert` (defaulting to `Invert` if it's defined)?

**Comment by tarcieri** [comment]
https://github.com/RustCrypto/traits/pull/894 implemented the proposed changes:

- `CtOption` is no longer a mandatory part of the return type for `Invert`
- The blanket impl of `Invert` returns a `CtOption`
- The impl of `Invert` for `NonZeroScalar` now infallibly returns a `NonZeroScalar`
