### ISSUE TITLE
Can p256::{AffinePoint,ProjectivePoint}::generator() be a `const fn`?

### ISSUE THREAD

**Issue by isislovecruft** [RustCrypto/elliptic-curves#508]
Hi! This might be an entirely silly question, but is there any reason why the basepoint() functions in the p256 crate cannot be `const fn`?

Edit: Also, somewhat tangential question, is there any reason why these implementations do not have precomputed multiples of the basepoint as tables for speeding up scalar multiplication?

Thanks for all your hard work in building and maintaining these libraries!

**Comment by tarcieri** [comment]
The current `generator` method of `AffinePoint` is actually the `PrimeCurveAffine::generator` trait method.

We could define an inherent `const fn` with the same name (since `const impl` isn't stable yet), but another option is to add an inherent `AffinePoint::GENERATOR` constant instead, and have `PrimeCurveAffine::generator` return that.

`ProjectivePoint`'s `generator` is the `Group::generator` method, but we could similarly add an inherent `ProjectivePoint::GENERATOR` constant instead.

> Edit: Also, somewhat tangential question, is there any reason why these implementations do not have precomputed multiples of the basepoint as tables for speeding up scalar multiplication?

As you can probably guess given your `const fn` questions, while we've wanted to add these tables, we'd like to compute them using `const fn` now that that's nearly possible. However, there are still some gaps like the ones you're raising in this issue.

**Comment by newpavlov** [comment]
>since `const impl` isn't stable yet

IIRC it does not even have an accepted RFC yet.

**Comment by tarcieri** [comment]
Aah, so one major blocker on this that maybe you can help with @isislovecruft.

`AffinePoint` has a `infinity: Choice` struct field which is used for representing the identity point.

However, there is no way to initialize this in a const context. So we'd need some sort of minimal `const fn` support for `Choice`.

**Comment by tarcieri** [comment]
I found a solution for `const fn` and `Choice`: #510 

It models `infinity` as a `u8` instead of a `Choice` to enable const constructors. The `is_infinity` method converts to a `Choice` on-the-fly.

**Comment by tarcieri** [comment]
#511 does the same treatment for `k256`.

Both crates now have `IDENTITY` and `GENERATOR` inherent constants for both `AffinePoint` and `ProjectivePoint`, and the previous inherent methods to compute them are now deprecated.

Closing this.
