### ISSUE TITLE
How to convert a VerifyingKey of type FieldElement10x26 to a FieldElement5x52 type

### ISSUE THREAD

**Issue by nihaoqingtuan** [RustCrypto/elliptic-curves#989]
When I execute the following code, the result is of type FieldElement10x26, likely due to running it in the context of a third-party library. However, when I attempt to verify using it, the verification fails. Therefore, I am inquiring about how to convert it to FieldElement5x52 or if the inability to verify is due to the environment.

` let pk_string = "0425c919aa487e577cc361f43a9b81f3484286ac6132c9eff047ec6eca6c1dcc89200c1bf5d6da42a8206a2f01b585d35ea05c2648050f3dd4c98fc0b87f5191e5";
        let byte = hex::decode(pk_string).expect("123");
        let vk = VerifyingKey::from_sec1_bytes(&byte).expect("456");
        println!("vk: {:?}", vk); `
        
     
result：
vk: VerifyingKey { inner: PublicKey { point: AffinePoint { x: FieldElement(FieldElement10x26([1952905, 52146843, 50267262, 25479975, 4359852, 48266450, 35603369, 22934285, 27936894, 619078])), y: FieldElement(FieldElement10x26([55677413, 66072095, 64834712, 18879548, 44063782, 23164119, 44232731, 17473665, 66442970, 525062])), infinity: 0 } } }

**Comment by hsxyl** [comment]
I also meet this problem, can I ask how you solved it?

**Comment by tarcieri** [comment]
These are types which are internal to `k256`. You can't directly convert them.

They're two different representations based on 32-bit or 64-bit limbs. Only one should be active at a given time.

We should probably hide this implementation detail from the `Debug` output.

**Comment by hsxyl** [comment]
Thanks, I read the code and understand what you're saying. However, the scenario I have now encountered is that I use a 32-bit limbs (10×26) environment in wasm, but when the  FieldElement10x26 public bytes transfered by the network to the blockchain for verification, there is a problem, while the FieldElement5x52 public key verification is no problem. This is probably because the target blockchain platform is not compatible, but I can't ask the target blockchain platform to fix this in time, so I wonder if I can still use the FieldElement5x52 public key in wasm (32-bit limbs environment).

**Comment by tarcieri** [comment]
If there's a bug in the 32-bit code, that would be important to know. Can you make a reproduction?

**Comment by hsxyl** [comment]
Sorry, maybe my description is not very clear, this should not necessarily explain the bug of 32-bit code, in fact, I am building in a wasm platform to send the public key and signed information to a Go language implementation of the blockchain (cosmos) for verification. When I sent FieldElement10x26 public bytes, the validation failed. Because I wasn't familiar with Go language, so I wasn't completely sure which side was responsible for the bug(But I think a high probability is that the cosmos block chain does not handle the case of FieldElement10x26 public correctly). But sending FieldElement5x52 public key for verification is fine.

**Comment by hsxyl** [comment]
I temporarily circumvent this problem by generating the public key bytes data on the 64-bit platform and then uploading it to the 32-bit platform. If you have any other ideas, please let me know, thank you.

**Comment by tarcieri** [comment]
It's an internal implementation detail. The end-user facing API is the same. If there is any divergence between 32-bit and 64-bit, it's a bug.

cc @fjarri

**Comment by fjarri** [comment]
> when the FieldElement10x26 public bytes transfered by the network
> When I sent FieldElement10x26 public bytes

Could you elaborate on that? Anything transferable by wire should have no `FieldElement10x26` or `FieldElement5x52` in it, it should be either `x` or `(x, y)` coordinates of the point as scalars. Could you show the Rust part of the code that prepares the information you're sending?

**Comment by hsxyl** [comment]
Sorry, I have found it was a mistake on my part not caused by 32-bit or 64-bit.
